[package]
name = "tauri-plugin-cors-fetch"
version = "1.0.0"
description = "A Tauri plugin that enables seamless cross-origin resource sharing (CORS) for web fetch requests within Tauri applications."
keywords = ["tauri", "CORS", "fetch"]
authors = [ "Del Wang <hello@xbox.work>" ]
repository = "https://github.com/idootop/tauri-plugin-cors-fetch"
documentation = "https://docs.rs/tauri-plugin-cors-fetch"
readme = "README.md"
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/node_modules"]
links = "tauri-plugin-cors-fetch"

[dependencies]
tauri = { version = "2.0.0-beta.11" }
tauri-plugin-http = "2.0.0-beta.3"
once_cell = "1.19.0"
tokio = { version = "1.36.0", features = ["macros"] }

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta.9", features = ["build"] }
